//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prefinalMatiasCoccaro
{
    using ManejoTriangulos;
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form1
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;
        private object txtLadoA;
        private object txtLadoB;
        private object dataGridViewTriangulos;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prefinalMatiasCoccaro.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }


        internal static string Lado_A
        {
            get
            {
                return ResourceManager.GetString("Lado A", resourceCulture);
            }
        }

        internal static string Lado_B
        {
            get
            {
                return ResourceManager.GetString("Lado B", resourceCulture);
            }
        }


        internal static string Lado_C
        {
            get
            {
                return ResourceManager.GetString("Lado C", resourceCulture);
            }

        }
        private void MostraInformacionEnGrilla(Triangulo triangulo, double area)
        {
            // Calcular el perímetro, área y tipo de triángulo
            double perimetro = triangulo.CalcularPerimetro();
            double v = triangulo.CalcularArea();
            string tipoTriangulo = triangulo.DeterminarTipoTriangulo();

            // Mostrar la información en la grilla
            object value = dataGridViewTriangulos;
            double ladoA = triangulo.LadoA;
            double ladoB = triangulo.LadoB;
            double ladoC = triangulo.LadoC;
            string colorRelleno = triangulo.ColorRelleno;
            double perimetro1 = perimetro;
            double area1 = area;
            string tipoTriangulo1 = tipoTriangulo;
        }
    }
}